### ISSUE TITLE
Query Regarding Porting to following FPGA's

### ISSUE THREAD

**Issue by fabricchip** [ztachip/ztachip#11]
Hey there!
Can we port ztachip to the following FPGAs with less than 100,000 LUTs:
1. Digilent Cmod A7-35T: Artix-7 with 35,000 LUTs
2. Cmod A7-15T: Artix-7 FPGA Module with 15,000 LUTs
3. CrossLink NX from Lattice Semiconductors (LIFCL-40, 39,000 LUTs)

Please let me know any steps to follow

**Comment by ztachip** [comment]
Current version would fit a Xilinx Artix7-100 or Lattice ECP5-85
But I'm working on next version that would let you scale down to Artix7/35T. This is probably available by end of year.

________________________________
From: fabricchip ***@***.***>
Sent: March 11, 2024 3:01 AM
To: ztachip/ztachip ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ztachip/ztachip] Query Regarding Porting to following FPGA's (Issue #11)


Hello! Can we port ztachip to the following FPGAs with less than 100,000 LUTs:

  1.  Digilent Cmod A7-35T: Artix-7 with 35,000 LUTs
  2.  Cmod A7-15T: Artix-7 FPGA Module with 15,000 LUTs
  3.  CrossLink NX from Lattice Semiconductors (LIFCL-40, 39,000 LUTs)

Please let me know any steps to follow

**Comment by fabricchip** [comment]
Hi

Awesome, thanks for the info!


The board perfectly works on arty a7 for now. We will report back on
lattice ecp5.

Falling is among the most damaging event elderly people may experience.
With the ever-growing aging population, there is an urgent need for the
development of fall detection systems. We belive your repo is the best use
case for this project.

We are also going to port few ai models starting with human activity
recognition check it's performance.

https://github.com/CMU-Perceptual-Computing-Lab/openpose

1.https://github.com/aminullah6264/Activity_Rec_ML-LSTM


2.https://github.com/aminullah6264/Activity_Rec_ML-LSTM


This we are doing to solve the problem elderly fall detection.



Performance Question:


I have few questions regarding is there in particular command I can type
like htop or top to see memory usage dynamically and performance metrics.


Regards
Fabric Team

**Comment by fabricchip** [comment]
Hi,

Yes thanks for the info. Elderly care is our aim in this standlone device.
Sorry to hear about your aunt. We belive this is the most neglected part of
our aim to solve this using standlone FPGA based edge device...we would
want to run this as low cost FPGA device eventually . For now we will stick
to arty a7.

 We have made significant progress in compiling the code.
I just wanted to understand to integrate.

https://www.kaggle.com/models/google/movenet/frameworks/tensorFlow2/variations/multipose-lightning

Since tensorflowlite is already supported on ztachip.

We belive the following steps are important for integration:

1.Model Compatibility Check: Verify that all operations used by the PoseNet
model are supported by the ztachip TensorFlow Lite implementation. If there
are unsupported operations, you might need to implement these at the
compiler level. Is this correct assumption?

2.Create New Application: In the SW/apps directory, create a new directory
specifically for your PoseNet application. This directory will contain all
the necessary code to run PoseNet.

3.Implement Application Logic: Use the existing TensorFlow Lite application
examples in SW/apps/nn as a reference. Adapt this logic to initialize and
run our PoseNet model, focusing on handling multi-person detection outputs.

3.Input and Output Processing: Implement logic for processing input (e.g.,
camera feed or static images) and for handling the output from PoseNet
(e.g., drawing skeletons on images or calculating pose scores).

4.Test and Validation:Run our application on the ztachip development kit
and Measure the performance (inference time, accuracy, etc.) of your
PoseNet model on the ztachip hardware.


Our Development Plan:

1.Load model Function: SW/apps/nn/model_loader.cpp
(Hypothetical.location)

2.PreprocessInput Function:This function would handle the conversion of
input images or video frames to the format expected by PoseNet, such as
resizing, normalization, and color conversion.
(preprocess.cpp)

3.RunInference Function: The core function where the model inference
happens. It involves feeding the processed input to the model and
retrieving the output.
Possible Location: SW/apps/nn/pose_net_inference.cpp (hypothetical path).

4.ParseOutput Function: After inference, this function interprets the
output tensor(s) from PoseNet to extract pose information, such as keypoint
locations and confidence scores.
Possible Location: SW/apps/nn/output_parser.cpp (hypothetical path)


5.DrawPoses Function: If you plan to visualize the results by drawing
keypoints and skeletons on images, you'll need a function for this purpose.
Possible Location: SW/apps/nn/visualize.cpp (hypothetical path)


6.Compiler Modifications (If Needed based on ztachip architect.feedback)
AddOperation Support: If PoseNet uses TensorFlow Lite operations not
supported by ztachip, you'll need to implement these in the compiler. This
involves modifying the lexer (Lexer.l), parser (Parser.y), and potentially
adding new instruction generation logic (gen.cpp).



Do we need to modify any existing compiler modifications for this
implementation?

Please do let me know if this process we are following is going good or any
modifications are necessary.

Regards
Team fabric

**Comment by ztachip** [comment]
________________________________

**Comment by ztachip** [comment]
In few weeks, there will be a new ztachip release with micropython support.
Then you also have many of the features available from micropython like networking, file system, web, ...
There is also good community support for micropython
It runs just as fast as native C/C++ since python is used primarily just to setup the graph, all processing is still native speed

________________________________

**Comment by fabricchip** [comment]
Wow that's quick and elaborate. So the main program is vision
SW/src/vision_ai.cpp.

Thanks for pointing out that and also no need to create a new folder
posenet , just a new layer file to be done under nn.

Rest is vision_ai.cpp

Thank you we will follow and update you.

Only one question: does ztachip parallel process work in "dynamic shape
input" since nvidia cuda cores don't work for dynamic shape input, in this
particular mutipose model.

{
https://www.kaggle.com/models/google/movenet/frameworks/tensorFlow2/variations/multipose-lightning
}

Handling Dynamic Input Shapes:

Dynamic Shape Support: Advanced AI models, including those for pose
estimation that handle varying numbers of detections, require support for
dynamic input shapes.
 The ztachip platform might have mechanisms in place to handle tensors with
dynamic shapes, adjusting memory allocation and operation execution as
needed.
Is this assumption correct?

**Comment by aravindgp** [comment]
Wow you just released micropython code! "In few weeks, there will be a new ztachip release with micropython support.
Then you also have many of the features available from micropython like networking, file system, web.." Its good to learn this and I am sure our development will pickup pace on this micropython code you just released.

**Comment by fabricchip** [comment]
Awesome you have released micropython as indicated earlier this makes the job very easy to port and try out new models. Especially our posenet model. We are actively working on it. I am closing the issue for now this thread now.

**Comment by ztachip** [comment]
The model https://www.kaggle.com/models/google/movenet/frameworks/tensorFlow2/variations/multipose-lightning
On the website it shows only FP16 version.
You need to do an extra quantization step to INT8 for ztachip to work however.
If you can get this converted, I can give it a try for you.

________________________________

**Comment by fabricchip** [comment]
Sure, we will convert fp16 to int8 for multipose model. Its really worthy
the project.
