### ISSUE TITLE
About LUTs

### ISSUE THREAD

**Issue by AugustZTR** [ztachip/ztachip#3]
Hello, I encountered a problem while trying to deploy the project.
When I run implementation in Vivado, it says the LUTs over-utilizad. I wonder why would that happend as I used the same FPGA board as mentioned in the readme.

**Comment by AugustZTR** [comment]
use older version vivado

**Comment by ztachip** [comment]
Im using Vivado2020.2
The provided example is based on Artix-7/100
This chip has 100K LUT and should be enough for max configuration (8 cores)
