### ISSUE TITLE
About Video Output

### ISSUE THREAD

**Issue by AugustZTR** [ztachip/ztachip#4]
Hello, I compiled and wrote the program according to the document, and successfully used GDB for communication and program loading, however, I have not been able to get the output of the video screen, i'm not sure if it's the video output or if the program isn't working properly

**Comment by ztachip** [comment]
Which FPGA board are you using?
If you are using the Arty-A7, can you try the project as is from github first? That should work fine.
If you create your own project, verify if your pin assignments for VGA are programmed correctly.

**Comment by AugustZTR** [comment]
I'm using the same Arty-A7 100T as the project and still not figure out the reason.

**Comment by ztachip** [comment]
But if you build ztachip project from git as is. Does it work?
Try to download latest ztachip again and open the project below to build
ztachip/HW/examples/GHRD/GHRD.xpr

**Comment by AugustZTR** [comment]
I tried again and still not work.
The terminal output is like this
![图片](https://user-images.githubusercontent.com/28720897/224656013-759a12be-fcff-41db-b06b-c9d0427f458e.png)

**Comment by AugustZTR** [comment]
I tried again and still not work.
Here is the terminal output.
![图片](https://user-images.githubusercontent.com/28720897/224657983-f19b54ba-7378-4e6a-965e-477d645cb1bc.png)
And here is the hardware.
![图片](https://user-images.githubusercontent.com/28720897/224658365-d52874a3-2cb9-416d-9479-a982367f8ff8.png)

**Comment by AugustZTR** [comment]
Sorry, my bed. I mistook the following output as the "continue" command mentioned in the document
![图片](https://user-images.githubusercontent.com/28720897/224982776-fe67502e-3bee-4104-9b5a-be6ad2adaec2.png)
However, this has brought new problems. The board will reset after I input the "continue". I repeated the complete process on two computers respectively, and the result was the same. And still, no video output.
![图片](https://user-images.githubusercontent.com/28720897/224983449-fef2681d-8e33-4e3f-9b29-15b12deb6058.png)

**Comment by ztachip** [comment]
Looks like you have problem with the openOCD or USB connection.
Can you verify you setup correctly. The steps to setup this also on github page.
Make sure the board is operational before starting openOCD. Usually after power up, it takes 10sec before FPGA is programmed (you will see a green led turn on)

________________________________

**Comment by ztachip** [comment]
Does it work for you?

**Comment by ztachip** [comment]
Done
