### ISSUE TITLE
Video Output got stuck

### ISSUE THREAD

**Issue by explorer1100** [ztachip/ztachip#9]
![capture](https://github.com/ztachip/ztachip/assets/108859093/add5a81e-ff05-44f3-a413-b35208c77f0a)

After executing the program with the "continue" command, I observed that the output displayed on the monitor remains static for only one second. Subsequently, it becomes unresponsive and does not update, persisting in a frozen state even after pressing button 0.

**Comment by ztachip** [comment]
Looks like your connection of webcam is not solid.
________________________________
From: umesh-deepgrid ***@***.***>
Sent: February 5, 2024 7:46 AM
To: ztachip/ztachip ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ztachip/ztachip] Video Output got stuck (Issue #9)


capture.jpg (view on web)<https://github.com/ztachip/ztachip/assets/108859093/add5a81e-ff05-44f3-a413-b35208c77f0a>

After executing the program with the "continue" command, I observed that the output displayed on the monitor remains static for only one second. Subsequently, it becomes unresponsive and does not update, persisting in a frozen state even after pressing button 0.

**Comment by umesh-deepgrid** [comment]
I've examined all my connections, and they seem quite secure. However, despite this, the screen continues to freeze.

**Comment by ztachip** [comment]
Try to run in test mode first to make sure firmware are ok
in SW/makefile change UNIT_TEST=true
Recompile everything
If your FPGA works, then you should have blinking led.
Try to also move/hold the pins to see if it is making any changes. Sometimes the pin connections are loose even if it looks solid.
I also apply some glue to keep the pins together.
________________________________

**Comment by explorer1100** [comment]
I adhered to the provided instructions, but unfortunately, there was no noticeable alteration. The only output I observed was a constant red and green LED illumination, with the green LED not exhibiting any blinking on the board. I have included a picture for your reference. Additionally, I have a question regarding a warning message I encounter when launching OpenOCD, which is attached here. I used 30cm Male to Female Jumper Wires to connect the camera to the board. I'm curious if the wire length might be a factor causing the issue and would appreciate clarification on this matter.
![ztachip1](https://github.com/ztachip/ztachip/assets/108859093/c77c7bb8-773b-4e91-9480-dbc79053c51e)
![ztachip2](https://github.com/ztachip/ztachip/assets/108859093/0ea69e1f-d073-4530-8dc9-e256a5f5f82b)

**Comment by ztachip** [comment]
After loading program, confirm program is running using gnu debugger command
Also hit ctrl+c to see program still running or crashing. Or set breakpoint in main
Check that your tool chain is built correctl according to ztachip weɓsite

________________________________

**Comment by ztachip** [comment]
After loading program, instead of continue command, try step command to see how far it runs
Confirm that your tool chain is built with correct risc5 option

________________________________

**Comment by ztachip** [comment]
Please try latest ztachip release if it still does not work for you

**Comment by explorer1100** [comment]
I just wanted to inform you that I'm working on it, and it will likely take a day or two. I'm starting fresh from scratch.

**Comment by explorer1100** [comment]
Hi, as per your recommendation, I located the RISC-V version and compiler version. Here are the details:

```
explorer@ubuntu:~/ztachip/SW/src$ riscv32-unknown-elf-gcc --version
riscv32-unknown-elf-gcc () 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

explorer@ubuntu:~/ztachip/SW/src$ riscv32-unknown-elf-gcc -v
Using built-in specs.
COLLECT_GCC=riscv32-unknown-elf-gcc
COLLECT_LTO_WRAPPER=/opt/riscv/libexec/gcc/riscv32-unknown-elf/13.2.0/lto-wrapper
Target: riscv32-unknown-elf
Configured with: /home/explorer/riscv-gnu-toolchain/gcc/configure --target=riscv32-unknown-elf --prefix=/opt/riscv --disable-shared --disable-threads --enable-languages=c,c++ --with-pkgversion= --with-system-zlib --enable-tls --with-newlib --with-sysroot=/opt/riscv/riscv32-unknown-elf --with-native-system-header-dir=/include --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --disable-tm-clone-registry --src=.././gcc --disable-multilib --with-abi=ilp32 --with-arch=rv32im --with-tune=rocket --with-isa-spec=20191213 'CFLAGS_FOR_TARGET=-Os    -mcmodel=medlow' 'CXXFLAGS_FOR_TARGET=-Os    -mcmodel=medlow'
Thread model: single
Supported LTO compression algorithms: zlib
gcc version 13.2.0 ()     
```

Following your advice, I utilized the step command, which resulted in a blank screen. Despite rebuilding ztachip, RISC-V, and openocd from the beginning, the freezing issue on the screen persists.

**Comment by ztachip** [comment]
Try again with latest ztachip.
I have posted new version 2 days ago.
Before execute continue command, first check the memory content first to confirm SW loaded correctly with x command
It should look like below

(gdb) x 0
0x0 <crtStart>:   0x00002137
(gdb) x 4
0x4 <crtStart+4>: 0xb9410113
(gdb) x 8
0x8 <crtStart+8>: 0x000100e7
(gdb) x 12
0xc <crtStart+12>:      0x00000013
(gdb) x 16
0x10 <taskEntry>: 0xff010113
(gdb)


________________________________

**Comment by explorer1100** [comment]
Hello, I've managed to get it running smoothly now. I believe the problem was with my previous setup using Oracle VirtualBox, but now that I'm running it on a full Ubuntu desktop system, everything is working properly.

**Comment by ztachip** [comment]
Perfect
Please check in in a month's time, you will be able to run your applications from micropython.

________________________________
